apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ticketing-staging
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/overlays/staging
    repoURL: https://github.com/naren9876/ticketing-infrastructure.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5
    syncOptions:
    - CreateNamespace=true
