apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    spec:
      imagePullSecrets:
      - name: ecr-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  template:
    spec:
      imagePullSecrets:
      - name: ecr-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
spec:
  template:
    spec:
      imagePullSecrets:
      - name: ecr-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
spec:
  template:
    spec:
      imagePullSecrets:
      - name: ecr-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  template:
    spec:
      imagePullSecrets:
      - name: ecr-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  template:
    spec:
      imagePullSecrets:
      - name: ecr-secret
