apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base configuration
bases:
  - ../../base

# Patch replicas for all deployments: 2 → 3
replicas:
  - name: api-gateway
    count: 3
  - name: user-service
    count: 3
  - name: movie-service
    count: 3
  - name: booking-service
    count: 3
  - name: payment-service
    count: 3
  - name: notification-service
    count: 3

# Common labels for staging
commonLabels:
  environment: staging
  version: v1

# Override image tags for staging deployment
images:
  - name: 840080485121.dkr.ecr.us-east-1.amazonaws.com/ticketing-api-gateway
    newTag: v1.0.10
  - name: 840080485121.dkr.ecr.us-east-1.amazonaws.com/ticketing-user-service
    newTag: v1.0.10
  - name: 840080485121.dkr.ecr.us-east-1.amazonaws.com/ticketing-movie-service
    newTag: v1.0.10
  - name: 840080485121.dkr.ecr.us-east-1.amazonaws.com/ticketing-booking-service
    newTag: v1.0.10
  - name: 840080485121.dkr.ecr.us-east-1.amazonaws.com/ticketing-payment-service
    newTag: v1.0.10
  - name: 840080485121.dkr.ecr.us-east-1.amazonaws.com/ticketing-notification-service
    newTag: v1.0.10
