apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ticketing-ai-workloads
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/naren9876/ticketing-infrastructure.git
    targetRevision: main
    path: kubernetes/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-models
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
